---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kata-dynamic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-kata-lvm