---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-kata-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-kata
  storageClassName: csi-kata-lvm